### PR TITLE
Miscellaneous refinements

### PR DESCRIPTION
**Pull request by Spappz**
Made some refinements to the following items:

### Aid (spell)
The AE was targetting `@attributes.hp.max` rather than `@attributes.hp.tempmax`, which is more appropriate given the increased maximum HP is, well, temporary. I also removed the second argument of the AE's macro, since it seemed completely unused by the macro itself.

### Enhance Ability (spell)
This was quite badly bugged (virtually unusable) when I _began_ this, but I only _just now_ realise that the actual cause wasn't Midi SRD but a DAE bug (fixed v11.1.8; see [first bullet](https://gitlab.com/tposney/dae/-/blob/v11/Changelog.md#anchor-1118))! The new macro is a complete rewrite, but:
- No longer references the `dnd5e.powerfulBuild` flag (which is good because _enhance ability_ stacks with Powerful Build, but the flag doesn't and would remove it on expiry from a creature that naturally has it)
- Reads nicer in code and looks nicer on-screen (formatting shamelessly ~~stolen from~~ inspired by DFCE) 😁

https://github.com/thatlonelybugbear/midi-srd/assets/34202141/7bcdfcfd-fcf9-4787-a7e4-f2aa5a23bc7a

### Feral Instinct (barbarian class feature)
The attached AE was called "New Active Effect". Now it's called "Feral Instinct".

### Heroism (spell)
A few things:
- The spell contained an item macro which... was a full duplicate of the function in the `MidiMacro` class. So now the item macro actually calls the module's function.
- The previously had a damage roll that was just `@mod[none]`, which was then fed into the item macro using the `@damage` argument. I removed that damage roll, since it wasn't very nice to look at in the chat card, and simply passed `@mod` directly into item macro.
- The macro now only posts chat messages when something happens unprompted. The chat messages also include a little more information than before. I wasn't sure '[target] gains heroism' is a useful message, when nothing mechanical happens (_heroism_ triggers on the target's turn) and the user is already notified by the AE-application itself!

---

Let me know if you'd like any adjustments!

### CODE REVIEW

**Comment by thatlonelybugbear** [comment]
I am away for a few days without access to my server, so I will take a look as soon as possible.

Thanks for taking the time to submit this MR 👍

**Comment by thatlonelybugbear** [comment]
I had 0 free time lately, as we were moving houses. I will take a look at all this soon :)

Sorry about that.

**Comment by Spappz** [comment]
No worries, hope your moving is smooth!

**Comment by Spappz** [comment]
Just a gentle prod here; no worries if you're still busy 😅

Hope the move went well!

**Comment by thatlonelybugbear** [comment]
Hey there, sorry for the delay.

I will push out the fixes on Monday that I am back home for a final v2.4 dnd5e compatible version and then finish at last a rewrite (for the v3 only though).

**Review by thatlonelybugbear — APPROVED** [review]

**Comment by thatlonelybugbear** [comment]
Thanks for that 👍

**Comment by thatlonelybugbear** [comment]
Actually I need to change some more stuff around so it's not ready to be released yet, but working on it :)
I don't think I'll be able to finish the changes tonight.

One point about Enhance Ability. Do you use Advanced Macros module? Otherwise the proposed way won't be able to update any actors not owned by the player (would work for the GM fine).

**Comment by Spappz** [comment]
Oops, didn't see this comment 😅

> Do you use Advanced Macros module? 

In all honesty? I don't remember—I _used_ to have it on, then I remember reading (somewhere) that Midi/DAE had absorbed its functionality and that Advanced Macros was effectively defunct, so I disabled it. I then later re-enabled it after encountering some bugs but, due to my 5e campaign coming to an end very soon, was admittedly not bothered enough to investigate further, so I simply re-enabled AM. I have no idea at which point in this timeline I did the development for this PR 🤣

I see where the problem you're referring to is. Since Midi SRD relies on Midi-QoL, and Midi-QoL requires socketlib, and socketlib lets you execute macros as a GM... would it be possible to lever that? I note that Midi SRD _itself_ doesn't rely on socketlib (yet 😏) but it should work.

Alternatively, I note your macro works by _editing_ an effect that Midi has already applied on the target. I can instead reuse that workflow if that 'bypasses' the permissions for editing a non-owned actor—I'm just a little worried about edge-case bugs if there is a pre-existing AE called "Enhance Ability". Perhaps there could be a way to extract the applied AE's UUID via Midi? (If it works via another method I'm honestly stumped how your one works at all)

**Comment by thatlonelybugbear** [comment]
Hey there, I was working on other projects lately, but finally the time has time 😶‍🌫️ 

I will update MidiSRD over the next couple of days.
My main concern is that I will probably need to drop v2.4.1 dnd5e compatibility sooner than later. Will see how that goes

**Comment by Spappz** [comment]
Dropping v2.4.1 makes perfect sense. It'd be _nice_ if you can do one last version for it, but obviously that's dependent on how much extra effort is required.

**Comment by thatlonelybugbear** [comment]
At last working on this.
I will release over the next few days. It might need some more testing for 2.4.1, but after the release, any bugs/fixes should be happening much faster.

**Comment by Spappz** [comment]
Thank you for all your hard work!

**Pull request merged**
